export const FETCH_GRAFIC_REQUEST =  'FETCH_GRAFIC_REQUEST';
export const FETCH_GRAFIC_COMPLETE = 'FETCH_GRAFIC_COMPLETE';

export const FETCH_PERIOD_REQUEST =  'FETCH_PERIOD_REQUEST';
export const FETCH_PERIOD_COMPLETE = 'FETCH_PERIOD_COMPLETE';

export const  CHANGE_DATA_REQUEST = 'CHANGE_DATA_REQUEST';
export const CHANGE_DATA_COMPLETE = 'CHANGE_DATA_COMPLETE';
